language: node_js
node_js:
  - '11'
cache: yarn
script:
  - yarn test:unit

deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: firebase
  token:
    secure: ji68OGsU/Q6mJ0X5Ccj25QTXG7Ikg4rjL7wR3Md2yjjCoytlRoYsdB+6M7sW8u9cXiWAwRkKLC2Tset+lg0BxqWMwBOEz/7aJBWvGTaitgZjkjpEB7v/Yee5hfQuJUVGtjzjGGkbGjAomq3BPvl06sQ2RhS2mg97ALooEX3lqW/eicG7N10SeJ9ibA8P/QXZu+Xq+tj1GbGXvCHTEWD3CmZDG3oaOh43XoMHTW9sYpgdxa9nXHw+aItvfC1kJ0orgWHXIdMNSmkhlKwIoPTFA2nssrX8DEnL22VREAWmu4ltOP8MaEIe32x+vo4b+XYrik9EwvomnBRLCqkYlXSExcAO289QUER41JmPsW4wK/P2Lmgk6EccPGDmq2tay4V/NEc9kmKQU17JIQIqGeoOix7jH58BDZEGbOr9JVxL2aqn1uUfoDlixlKSqr2VNYZEscsh2tSzmvo6EiZEoClMlq3gCvRJ49a1wJlUBa3QALCmXIqn5UD+boHr7hH58bFamaqtDWPuN7EY/XfREEQM9iX9CaksTFovTpvzh0Q0Ai2mydPD324j6JycvWTeeM9Nwb9RSGMh0pbiRKhthhEpi6nNBoVdxHjiz3mijnGX5qkNaqtHdUv933gwzoxYQ+A+JqBYY8BZfu02PdwpaBgs2TlBZsaJh8YEPxsdVPXKB2I=
