language: node_js
node_js:
  - '11'
cache: yarn
script:
  - yarn test:unit --silent
deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: firebase
  token:
    secure: 6YT92rTp2WxdRcSChRAVVsAAmYOWpYl+afhcxOt+1HZsdRA6t2PFkptfUYNWmypCzc6A1SGcl/jVRCs2GZPpk09h6tvIc84B6tRypW/hVnBsf5I4Jm7X5h9Yx1hDa0xYE/pCFebH+2joRp+V/lTvsrqn+lmMUKi18vJotfvv8lVyhbZ25Ium8N+atmzhO+aZK/Cya+xHIvqh8PHPJuib3TV59qJpST0sVIOfjqmh8it2chmIvT8YSipyCj++qaSB0vZTTy0vC+pqBBn4hwCbUH7I3AiudJT1dNRyAIrz1TNqF1wdtZFrL8li6zyliygCIGZXh+VhSVQmVGOhenmTDRW/DaduhRBZWxXn6uIYvvErFWLukrhESBwEvicBK9ENXZnJToembj0yjZftnjbaf1bb0p3hhKgB9OsKkJ14gIs1Sam1Enxr0Whw/Qf4BwEnHEH+yhZW/+Ql9ZoQ+77vhRB9bNGWTDUNL+uIjjPZ0ITvAgMriyDlBAVY3OswCx3AVMjg1QkQZ6uiyBr9a8AYXxF9nKwkGp+hMuG3d7MbbujCVINNUuYXAcqRR0BntXz7PL/kFGVZF9tao+bi3pzEsKfK4E8Tv6fLTo2sK0MNf0Y3X+SivWQxOm3JmJnX+S37A2GMzPcw6Byr1ARsSbP1oO4zo72fIMntdqpowK/gsv4=
